models/user.py
from extensions import db


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=False)
    email = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200))
    created_at = db.Column(db.DateTime(), nullable=False, server_default=db.func.now())
    update_at = db.Column(db.DateTime(), nullable=False, server_default=db.func.now(), onupdate=db.func.now())

    @property
    def data(self):
        return {
            'id':self.id,
            'name':self.name,
            'email':self.email,
            'password':self.password
        }
    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all(cls):
        r = cls.query.all()
        result =[]

        for i in r:
            result.append(i.data)
        return result
    
    @classmethod
    def get_by_id(cls,id):
        return cls.query.filter(cls.id == id).first()


class User1(db.Model):
    __tablename__ = 'users1'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=False)
    email = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200))
    pekerjaan = db.Column(db.String(200))
    gender = db.Column(db.String(200))
    umur = db.Column(db.String(200))
    created_at = db.Column(db.DateTime(), nullable=False, server_default=db.func.now())
    update_at = db.Column(db.DateTime(), nullable=False, server_default=db.func.now(), onupdate=db.func.now())

    @property
    def data(self):
        return {
            'id':self.id,
            'name':self.name,
            'email':self.email,
            'password':self.password,
            'pekerjaan':self.pekerjaan,
            'gender':self.gender,
            'umur':self.gender,

        }
    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all(cls):
        r = cls.query.all()
        result =[]

        for i in r:
            result.append(i.data)
        return result
    
    @classmethod
    def get_by_id(cls,id):
        return cls.query.filter(cls.id == id).first()

app.py
from flask import Flask, render_template
from config import Config
from extensions import db 
from flask_migrate import Migrate
from routes import main

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    register_resources(app)
    register_extensions(app)
    return app

def register_extensions(app):
    db.init_app(app)
    migrate = Migrate(app,db)

def register_resources(app):
    app.register_blueprint(main)


if __name__ == '__main__':
    app = create_app()
    app.run('127.0.0.1',5000)

controllers/user.py
from flask import request
from models.user import User, User1
from extensions import db

def add_user_function():
    if request.method == "POST":
        name=request.form['name']
        email=request.form['email']
        password= request.form['password']
        user= User1(
            name=name,
            email=email,
            password=password
        )

        user.save()
        data = {
            'id':user.id,
            'name':user.name,
            'email':user.email,
            'password':user.password
        }
        return data
    
def edit_user_function(data):
    if request.method == "POST":
        data.name =request.form['name']
        data.email=request.form['email']
        data.password = request.form['password']

        db.session.commit()
        return data

def delete_user_function(user):
    db.session.delete(user)
    db.session.commit()

def register_user_function(name, email, password):
    try:
        # Create a new user object
        new_user = User1(name=name, email=email, password=password)
        db.session.add(new_user)
        db.session.commit()
        return new_user
    except Exception as e:
        print(e)
        return None


def login_user_function(email, password):
    try:
        user = User.query.filter_by(email=email).first()
        if user and user.password == password:  # Anda mungkin ingin menggunakan hashing password yang aman di sini
            return user
        else:
            return None
    except Exception as e:
        print(e)
        return None


def loginuser_user_function(email, password):
    try:
        user = User1.query.filter_by(email=email).first()
        if user and user.password == password:  # Anda mungkin ingin menggunakan hashing password yang aman di sini
            return user
        else:
            return None
    except Exception as e:
        print(e)
        return None

routes.py
from flask import Blueprint, render_template, redirect, url_for, request, session
from controllers.user import add_user_function, edit_user_function, delete_user_function, register_user_function, login_user_function,loginuser_user_function
import sys 
from models.user import User, User1

main = Blueprint('main', __name__) #routename= main

@main.route('/', methods=['GET'])
def home():
    data = User.get_all()
    return render_template('index.html', data=data)

@main.route('/adduser',methods = ['GET','POST'])
def add_user():
    data = add_user_function()
    #print(data, files=sys.stderr)
    return render_template('adduser.html', data=data)

@main.route('/edituser/<int:id>',methods = ['GET','POST'])
def edit_user(id):
    user = User1.get_by_id(id)
    data = edit_user_function(user)

    return render_template('edituser.html', user=user, data=data)

@main.route('/deleteuser/<int:id>', methods=['POST'])
def delete_user(id):
    user = User1.get_by_id(id)
    print(user,file=sys.stderr)
    delete_user_function(user)
    return redirect(url_for('main.home_page'))

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        
        if email == 'admin@gmail.com' and password == 'admin':
            return redirect(url_for('main.home_page'))
        else:
            return "Invalid credentials", 401
    
    # Jika method GET, tampilkan halaman login
    return render_template('login.html')

@main.route('/loginuser', methods=['GET', 'POST'])
def loginuser():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = loginuser_user_function(email, password)
        if user:
            return redirect(url_for('main.home_user'))
        else:
            return "Invalid credentials", 401
    return render_template('loginuser.html')

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        user = register_user_function(name, email, password)
        if user:
            return redirect(url_for('main.loginuser'))
        else:
            return "Registration failed", 400
    return render_template('register.html')

@main.route('/home', methods=['GET'])
def home_page():
    data = User1.get_all()
    return render_template('home.html', data=data)

@main.route('/homeuser', methods=['GET'])
def home_user():
    data = User1.get_all()
    return render_template('homeuser.html', data=data)

templates/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> 
                            <a href="/home">Back to Home</a>
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 pd-md--0 mb-md-5 px-md-2 text-center">Add User</h2>
                        <form method="POST" action="/adduser">
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder="Name"/><br/>
                            </div>

                            <div class="form-group">
                                <input type="email" id="email" name="email" class="form-control" placeholder="email"/><br/>
                            </div>

                            <div class="form-group">
                                <input type="password" id="password" name="password" class="form-control" placeholder="password"/><br/>
                            </div>
                            <br/>
                            <br/>
                            <input type="submit" class="btn btn-success text-center">
                        </form>

                    </div>

                </div>

            </div>
        </div>


    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>
</html>

templates/edituser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> 
                            <a href="/home">Back to Home</a>
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 pd-md--0 mb-md-5 px-md-2 text-center">Edit User</h2>
                        <form method="POST" action="/edituser/{{ user.id }}">
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder={{user.name}}/><br/>
                            </div>

                            <div class="form-group">
                                <input type="email" id="email" name="email" class="form-control" placeholder={{user.email}}/><br/>
                            </div>

                            <div class="form-group">
                                <input type="password" id="password" name="password" class="form-control" placeholder={{user.password}}/>
                            </div>
                            <br/>
                            <br/>
                            <input type="submit" class="btn btn-success text-center">
                        </form>

                    </div>

                </div>

            </div>
        </div>


    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>
</html>

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <script>
      function confirmDelete(user_id){
        var confirmation = confirm("Are you sure want to delete this user?")
        if(confirmation){
          var form = document.createElement('form');
          form.method='POST'
          form.action = '/deleteuser/'+user_id;
          document.body.appendChild(form);
          form.submit();
        }


      }
    </script>
  </head>
  <body>
    <div class="my-5 text-center">
        <button type="button" class="btn btn-primary" >
            <a href="{{url_for('main.add_user')}}" class="text-white"> Add User </a>
        </button>

        <br/>
        <div class="w-70 d-flex p-5">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  
                    {% for item in data%}
                    <tr>
                      <th scope="row">{{item.id}}</th>
                      <td>{{item.name}}</td>
                      <td>{{item.email}}</td>
                      <td>
                          <a href="/edituser/{{item.id}}"><button class="btn btn-success">Edit</button></a>
                          <button class="btn btn-danger" type="button" onclick="confirmDelete('{{item.id}}')">Delete</button>
                      </td>
                    </tr>
                    {% endfor %}
                  
                </tbody>
              </table>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/homeuser.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <script>
      function confirmDelete(user_id){
        var confirmation = confirm("Are you sure want to delete this user?")
        if(confirmation){
          var form = document.createElement('form');
          form.method='POST'
          form.action = '/deleteuser/'+user_id;
          document.body.appendChild(form);
          form.submit();
        }


      }
    </script>
  </head>
  <body>
    <div class="my-5 text-center">

      <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item justify-content-center text-center">
                <a href="/"> Logout</a>
            </li>
        </ol>
    </nav>

        <br/>
        <div class="w-70 d-flex p-5">
          
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Pekerjaan</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Umur</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  
                    {% for item in data%}
                    <tr>
                      <th scope="row">{{item.id}}</th>
                      <td>{{item.name}}</td>
                      <td>{{item.email}}</td>
                      <th>{{item.pekerjaan}}</th>
                      <th>{{item.gender}}</th>
                      <th>{{item.umur}}</th>
                      <td>
                          <a href="/edituser/{{item.id}}"><button class="btn btn-success">Edit</button></a>
                          <button class="btn btn-danger" type="button" onclick="confirmDelete('{{item.id}}')">Delete</button>
                      </td>
                    </tr>
                    {% endfor %}
                  
                </tbody>
              </table>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  <div class="my-5 text-center">
    <a href="{{url_for('main.loginuser')}}" class="btn btn-secondary text-white mx-2">Login Customer</a>
    <a href="{{url_for('main.login')}}" class="btn btn-secondary text-white mx-2">Login Admin</a>

    <a href="{{url_for('main.register')}}" class="btn btn-secondary text-white mx-2">Register Customer</a>
</div>

</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  
</body>
</html>

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2 class="mb-4 text-center">Login</h2>
                <form method="POST" action="{{ url_for('main.login') }}">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Login</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/loginuser.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Customer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> 
                            <a href="/">Back to Home</a>
                        </li>
                    </ol>
                </nav>
                <h2 class="mb-4 text-center">Login Customer</h2>
                <form method="POST" action="{{ url_for('main.loginuser') }}">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Login</button>
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"> 
                                <a href="/register">Register</a>
                            </li>
                        </ol>
                    </nav>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> 
                            <a href="/">Back to Home</a>
                        </li>
                    </ol>
                </nav>
                <h2 class="mb-4 text-center">Register</h2>
                <form method="POST" action="{{ url_for('main.register') }}">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control" placeholder="email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control" placeholder="password">
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Register</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>